#' This function exports a shapefile to a postgreSQL database.
#' @export
#' @title Add a shapefile to a postgreSQL database
#' @name sendShape
#' @param con An object of class "pgConnect" generated by pgConnect()
#' @param folder String with the folder containing the shapefile
#' @param layer A string with the name of shapefile (without the .shp extension)
#' @param pgLayer A string with the name of the layer in the database. Optional
#' @return None
#' @author Bruno Silva
sendShape <- function(con, folder, layer, pgLayer = NULL){
  if(is.null(pgLayer)) pgLayer = layer
  writeOGR(readOGR(folder, layer), 
           driver = "PostgreSQL",
           dsn = con[[2]],
           layer = pgLayer)
}
